questions = [
    "Who's most likely to accidentally send a text to the wrong person?",
    "Who's most likely to have a wardrobe malfunction in public?",
    "Who's had the most embarrassing moment in a public bathroom?",
    "Who's the clumsiest when they're drunk?",
    "Who's most likely to snort when they laugh?",
    "Who's had the most cringe-worthy date?",
    "Who's most likely to fart in a quiet room and pretend it wasn't them?",
    "Who's the worst at remembering people's names?",
    "Who's most likely to get caught picking their nose?",
    "Who's the worst at flirting?",
    "Who's most likely to get caught taking a selfie in an inappropriate place?",
    "Who's most likely to trip and fall in front of a crowd?",
    "Who's the worst at handling spicy food?",
    "Who's most likely to accidentally like an ex's social media post?",
    "Who's the worst at parallel parking?",
    "Who's most likely to snore loudly in public?",
    "Who's the most accident-prone person you know?",
    "Who's most likely to laugh at an inappropriate moment?",
    "Who's most likely to accidentally send an embarrassing email to the entire office?",
    "Who's the worst at imitating accents?",
    "Who's most likely to get caught singing in the shower?",
    "Who's most likely to get caught picking food out of their teeth with a fork?",
    "Who's most likely to have a wardrobe malfunction while dancing?",
    "Who's most likely to accidentally insult someone without realizing it?",
    "Who's most likely to get caught talking to themselves in public?",
    "Who's the most awkward around their crush?",
    "Who's most likely to spill a drink on someone else at a party?",
    "Who's most likely to laugh so hard they snort?",
    "Who's the worst at remembering birthdays?",
    "Who's most likely to accidentally reveal a secret they were supposed to keep?",
    "Who's most likely to have food stuck in their teeth during an important meeting?",
    "Who's the worst at handling a spicy food challenge?",
    "Who's most likely to get caught daydreaming during a meeting?",
    "Who's most likely to accidentally send a love message to their boss?",
    "Who's the clumsiest when they're nervous?",
    "Who's most likely to mispronounce a common word in a conversation?",
    "Who's most likely to laugh at a funeral?",
    "Who's most likely to accidentally walk into the wrong bathroom?",
    "Who's the worst at remembering people's birthdays?",
    "Who's most likely to get caught talking to themselves in traffic?",
    "Who's most likely to have their phone ring in a quiet movie theater?",
    "Who's most likely to have their pants rip in public?",
    "Who's most likely to get caught singing in the car at a red light?",
    "Who's most likely to send an embarrassing text to their ex?",
    "Who's most likely to accidentally like an old social media post while stalking someone?",
    "Who's most likely to get caught with their fly down?",
    "Who's most likely to laugh uncontrollably at an inappropriate joke?",
    "Who's most likely to have a cringe-worthy voicemail greeting?",
    "Who's most likely to accidentally insult their boss?",
    "Who's most likely to have their stomach growl loudly in a silent room?",
]
