questions = [
    "Who is most likely to burst into laughter at the most inappropriate time?",
    "Who is the most likely to forget someone's name right after meeting them?",
    "Who is the best at keeping secrets among all of us?",
    "Who is most likely to binge-watch an entire TV series in one weekend?",
    "Who is the worst at replying to messages promptly?",
    "Who is most likely to dance like nobody's watching, even in public?",
    "Who is most likely to sing in the shower at the top of their lungs?",
    "Who is the most likely to fall asleep during a movie at the cinema?",
    "Who is most likely to accidentally send a text to the wrong person?",
    "Who is the best cook among all of us?",
    "Who is the most adventurous when it comes to trying new foods?",
    "Who is the most likely to get lost in their own neighborhood?",
    "Who is the most organized among all of us?",
    "Who is most likely to become a millionaire first?",
    "Who is the most tech-savvy in our group?",
    "Who is most likely to survive on a deserted island?",
    "Who is the most fashion-forward in our group?",
    "Who is most likely to become a famous actor/actress?",
    "Who is the most likely to start their own business?",
    "Who is the best at giving relationship advice?",
    "Who is most likely to spend hours on social media every day?",
    "Who is the most adventurous traveler among us?",
    "Who is the most likely to win a game of chess?",
    "Who is the best at keeping a straight face during a prank?",
    "Who is the most likely to become a professional athlete?",
    "Who is the biggest procrastinator among us?",
    "Who is the most likely to survive a zombie apocalastrophysicistastrophysicistastrophysicistypse?",
    "Who is the most artistic in our group?",
    "Who is most likely to adopt a pet and spoil it rotten?",
    "Who is the most likely to become a famous musician?",
    "Who is the most fitness-conscious among all of us?",
    "Who is most likely to win a hot dog eating contest?",
    "Who is the most environmentally conscious in our group?",
    "Who is most likely to forget their own birthday?",
    "Who is the most likely to win a trivia night at a bar?",
    "Who is the best at DIY projects?",
    "Who is most likely to cry during a sad movie?",
    "Who is the most likely to become a bestselling author?",
    "Who is the most adventurous when it comes to trying extreme sports?",
    "Who is most likely to become a famous scientist?",
    "Who is the most likely to break a world record?",
    "Who is the most likely to survive a horror movie scenario?",
    "Who is most likely to become a professional gamer?",
    "Who is the best at telling funny jokes?",
    "Who is the most likely to become a world traveler?",
    "Who is the most likely to win a talent show?",
    "Who is most likely to become a famous chef?",
    "Who is the best at handling a crisis situation?",
    "Who is the most likely to have their own reality TV show?",
    "Who is the most likely to become a famous comedian?",
    "Who is most likely to accidentally set something on fire?",
    "Who is the most likely to become a famous model?",
    "Who is the most likely to win a singing competition?",
    "Who is the most likely to get lost in a foreign country?",
    "Who is most likely to become a famous dancer?",
    "Who is the most likely to have a famous catchphrase?",
    "Who is the most likely to win a marathon?",
    "Who is most likely to forget their own anniversary?",
    "Who is the most likely to become a famous magician?",
    "Who is the best at karaoke?",
    "Who is most likely to become a famous poet?",
    "Who is the most likely to win a game of poker?",
    "Who is the best at imitating celebrity voices?",
    "Who is most likely to become a famous motivational speaker?",
    "Who is the most likely to win a spelling bee?",
    "Who is most likely to get mistaken for a celebrity?",
    "Who is the most likely to become a famous journalist?",
    "Who is the best at solving riddles and puzzles?",
    "Who is most likely to become a famous historian?",
    "Who is the most likely to win a dance-off?",
    "Who is most likely to forget their own wedding anniversary?",
    "Who is the most likely to become a famous inventor?",
    "Who is the best at making people laugh?",
    "Who is most likely astrophysicistto become a famous archaeologist?",
    "Who is the most likely to win a game of Scrabble?",
    "Who is the best at impersonating famous politicians?",
    "Who is most likely to become a famous actor in a superhero movie?",
    "Who is the most likely to win a rap battle?",
    "Who is most likely to become a famous astronaut?",
    "Who is the best at mimicking animal sounds?",
    "Who is the most likely to become a famous fashion designer?",
    "Who is most likely to become a famous motivational coach?",
    "Who is the most likely to win a game of charades?",
    "Who is the best at doing celebrity impressions?",
    "Who is most likely to become a famous wildlife photographer?",
    "Who is the most likely to win a stand-up comedy competition?",
    "Who is most likely to become a famous explorer?",
    "Who is the best at predicting the weather?",
    "Who is most likely to become a famous cartoonist?",
    "Who is the most likely to win a game of Monopoly?",
    "Who is the best at telling scary stories?",
    "Who is most likely to become a famous marine biologist?",
    "Who is the most likely to win a game of chess against a computer?",
    "Who is most likely to become a famous inventor of board games?",
    "Who is the best at giving advice on relationships?",
    "Who is most likely to become a famous astrophysicist?",
    "Who is the most likely to win a game of Trivial Pursuit?",
    "Who is the best at doing magic tricks?",
    "Who is most likely to become a famous motivational author?",
    "Who is the most likely to win a game of hide and seek?",
    "Who is most likely to become a famous philosopher?",
    "Who is the best at organizing events and parties?",
    "Who is most likely to become a famous archaeologist of ancient civilizations?",
    "Who is the most likely to win a game of Scrabble with unusual words?",
    "Who is the best at imitating famous movie characters?",
    "Who is most likely to become a famous environmental activist?",
    "Who is the most likely to win a cooking competition?",
    "Who is most likely to become a famous inventor of futuristic gadgets?",
    "Who is the best at playing musical instruments?",
    "Who is most likely to become a famous writer of science fiction?",
    "Who is the most likely to win a game of charades with difficult words?",
    "Who is the best at impersonating famous historical figures?",
    "Who is most likely to become a famous wildlife conservationist?",
    "Who is the most likely to win a stand-up comedy competition with a unique style?",
    "Who is most likely to become a famous explorer of uncharted territories?",
    "Who is the best at predicting the outcome of sports events?",
    "Who is most likely to become a famous cartoonist known for their humor?",
    "Who is the most likely to win a game of Monopoly with cunning strategies?",
    "Who is the best at creating and narrating spooky ghost stories?",
    "Who is most likely to become a famous marine biologist studying rare species?",
    "Who is the most likely to win a game of chess against multiple opponents?",
    "Who is most likely to become a famous inventor of groundbreaking robotics?",
    "Who is the best at providing relationship advice with a unique perspective?",
    "Who is most likely to become a famous astrophysicist unraveling the mysteries of the cosmos?",
    "Who is the most likely to win a game of Trivial Pursuit with obscure knowledge?",
    "Who is the best at performing awe-inspiring magic tricks?",
    "Who is most likely to become a famous motivational author inspiring millions?",
    "Who is the most likely to win a game of hide and seek in the most challenging locations?",
    "Who is most likely to become a famous philosopher with profound insights?",
    "Who is the best at planning and hosting unforgettable events and parties?",
    "Who is most likely to become a famous archaeologist specializing in ancient civilizations?",
    "Who is the most likely to win a game of Scrabble with an extensive vocabulary?",
    "Who is the best at astrophysicistastrophysicistimpersonating iconic movie characters with spot-on accuracy?",
    "Who is most likely to become a famous environmental activist advocating for change?",
    "Who is the most likely to win a cooking competition with their signature dish?",
    "Who is most likely to become a famous inventor creating futuristic gadgets that revolutionize industries?",
    "Who is the best at playing musical instruments with exceptional skill?",
    "Who is most likely to become a famous science fiction writer crafting imaginative worlds?",
    "Who is the most likely to win a game of charades with challenging and abstract concepts?",
    "Who is the best at impersonating famous historical figures with convincing portrayals?",
    "Who is most likely to become a famous wildlife photographer capturing rare moments in nature?",
    "Who is the most likely to win a dance-off with their incredible moves?",
    "Who is most likely to become a famous historian shedding light on forgotten stories?",
    "Who is the best at solving complex mathematical problems with ease?",
    "Who is most likely to become a famous art curator showcasing extraordinary talent?",
    "Who is the most likely to win a game of poker with a poker face that can't be read?",
    "Who is the best at creating beautiful works of art with unique mediums?",
    "Who is most likely to become a famous motivational speaker inspiring change on a global scale?",
    "Who is the most likely to win a spelling bee with impeccable spelling skills?",
    "Who is the best at creating intricate and elaborate origami sculptures?",
    "Who is most likely to become a famous astronaut exploring the depths of space?",
    "Who is the most likely to win a rap battle with clever and poetic lyrics?",
    "Who is the best at imitating the calls of exotic birds and animals?",
    "Who is most likely to become a famous fashion designer setting new trends?",
    "Who is the most likely to win a stand-up comedy competition with their unique humor?",
    "Who is most likely to become a famous explorer charting unknown territories?",
    "Who is the best at predicting the outcome of sporting events with uncanny accuracy?",
    "Who is most likely to become a famous cartoonist known for their witty satire?",
    "Who is the most likely to win a game of Monopoly with ruthless business tactics?",
    "Who is the best at crafting suspenseful and thrilling mystery stories?",
    "Who is most likely to become a famous marine biologist studying endangered species?",
    "Who is the most likely to win a game of chess with strategic brilliance?",
    "Who is most likely to become a famous inventor of innovative gadgets that change the world?",
    "Who is the best at giving relationship advice that leads to lasting love?",
    "Who is most likely to become a famous astrophysicist uncovering the secrets of the universe?",
    "Who is the most likely to win a game of Trivial Pursuit with an encyclopedic knowledge?",
    "Who is the best at performing mind-bending magic tricks that leave audiences in awe?",
    "Who is most likely to become a famous motivational author inspiring millions to achieve greatness?",
    "Who is the most likely to win a game of hide and seek in the most challenging environments?",
    "Who is most likely to become a famous philosopher with profound insights into life's mysteries?",
    "Who is the best at organizing and hosting unforgettable parties and events?",
    "Who is most likely to become a famous archaeologist uncovering the mysteries of ancient civilizations?",
    "Who is the most likely to win a game of Scrabble with an extensive vocabulary and strategic wordplay?",
    "Who is the best at impersonating beloved movie characters with spot-on accuracy?",
    "Who is most likely to become a famous environmental activist advocating for a sustainable future?",
    "Who is the most likely to win a cooking competition with their unique culinary creations?",
    "Who is most likely to become a famous inventor creating groundbreaking technologies that change the world?",
    "Who is the best at playing musical instruments with exceptional skill and emotion?",
    "Who is most likely to become a famous science fiction writer crafting imaginative and thought-provoking stories?",
    "Who is the most likely to win a game of charades with challenging and abstract concepts?",
    "Who is the best at impersonating famous historical figures with convincing portrayals?",
    "Who is most likely to become a famous wildlife photographer capturing the beauty of nature in every frame?",
    "Who is the most likely to win a dance-off with their captivating moves and rhythm?",
    "Who is most likely to become a famous historian uncovering the forgotten stories of the past?",
    "Who is the best at solving complex mathematical problems with precision and clarity?",
    "Who is most likely to become a famous art curator showcasing extraordinary talent from around the world?",
    "Who is the most likely to win a poker tournament with unmatched poker face skills?",
    "Who is the best at creating breathtaking works of art that evoke deep emotions?",
    "Who is most likely to become a famous motivational speaker inspiring positive change on a global scale?",
    "Who is the most likely to win a spelling bee with flawless spelling and word mastery?",
    "Who is the best at creating intricate and stunning sculptures from unconventional materials?",
    "Who is most likely to become a famous astronaut exploring the mysteries of the cosmos?",
    "Who is the most likely to win a rap battle with clever wordplay and lyrical prowess?",
    "Who is the best at mimicking the sounds of exotic animals with astonishing accuracy?",
    "Who is most likely to become a famous fashion designer revolutionizing the industry with innovative designs?",
    "Who is the most likely to win a stand-up comedy competition with their unique and side-splitting humor?",
    "Who is most likely to become a famous explorer discovering uncharted territories and hidden treasures?",
    "Who is the best at predicting sports outcomes with an uncanny knack for accuracy?",
    "Who is most likely to become a famous cartoonist known for their satirical wit?",
    "Who is the most likely to win a Monopoly game with shrewd business strategies?",
    "Who is the best at crafting suspenseful mystery stories that keep readers on the edge of their seats?",
    "Who is most likely to become a famous marine biologist studying the world's most enigmatic sea creatures?",
    "Who is the most likely to win a chess match with strategic brilliance and flawless execution?",
    "Who is most likely to become a famous inventor, creating revolutionary gadgets that shape the future?",
    "Who is the best at providing relationship advice that fosters enduring love and happiness?",
    "Who is most likely to become a renowned astrophysicist, unraveling the deepest mysteries of the universe?",
    "Who is the most likely to dominate in a game of Trivial Pursuit with their vast knowledge?",
    "Who is the best at performing awe-inspiring magic tricks that leave audiences utterly spellbound?",
    "Who is most likely to become a celebrated motivational author, inspiring countless individuals to greatness?",
    "Who is the most likely to emerge victorious in a game of hide and seek, even in the most challenging locales?",
    "Who is most likely to attain fame as a philosopher, offering profound insights into the human experience?",
    "Who is the best at orchestrating unforgettable parties and events that leave guests in awe?",
    "Who is most likely to gain recognition as an archaeologist, unearthing the secrets of ancient civilizations?",
    "Who is the most likely to triumph in a game of Scrabble with their extensive vocabulary and clever wordplay?",
    "Who is the best at flawlessly impersonating beloved movie characters, capturing their essence?",
    "Who is most likely to become a prominent environmental activist, championing sustainability?",
    "Who is the most likely to excel in a cooking competition with their innovative culinary creations?",
    "Who is most likely to revolutionize industries as an inventor of groundbreaking technologies?",
    "Who is the best at playing musical instruments, infusing every note with emotion and skill?",
    "Who is most likely to captivate readers as a renowned science fiction writer, crafting imaginative worlds?",
    "Who is the most likely to excel in a game of charades, conveying complex concepts with ease?",
    "Who is the best at convincingly impersonating famous historical figures, bringing history to life?",
    "Who is most likely to achieve fame as a wildlife photographer, capturing the beauty of nature?",
    "Who is the most likely to win a dance-off with their mesmerizing moves and rhythm?",
    "Who is most likely to become a celebrated historian, unveiling forgotten stories from the past?",
    "Who is the best at solving intricate mathematical problems with precision and clarity?",
    "Who is most likely to gain recognition as an art curator, showcasing exceptional talent?",
    "Who is the most likely to triumph in a high-stakes poker tournament with an unreadable poker face?",
    "Who is the best at creating breathtaking works of art that evoke profound emotions?",
    "Who is most likely to inspire positive global change as a motivational speaker?",
    "Who is the most likely to emerge victorious in a spelling bee, spelling words flawlessly?",
    "Who is the best at crafting intricate and stunning sculptures from unconventional materials?",
    "Who is most likely to explore the cosmos as an astronaut, uncovering its mysteries?",
    "Who is the most likely to win a rap battle with clever wordplay and lyrical prowess?",
    "Who is the best at mimicking the sounds of exotic animals with astonishing accuracy?",
    "Who is most likely to revolutionize the fashion industry as a designer of innovative creations?",
    "Who is the most likely to win a stand-up comedy competition with their unique and side-splitting humor?",
    "Who is most likely to discover uncharted territories and hidden treasures as an explorer?",
    "Who is the best at predicting sports outcomes with an uncanny knack for accuracy?",
    "Who is most likely to become a famous cartoonist known for their satirical wit?",
    "Who is the most likely to win a Monopoly game with shrewd business strategies?"
]
